application: cardapiodiario
version: 1
runtime: python
api_version: 1
  
handlers:
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml

- url: .*
  script: main.py
